name: Upload Terraform Cloud Python Client

on:
  push:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: libre-works/openapi-terraform-cloud
          path: openapi-terraform-cloud

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Generate client.
        run: |
          mkdir src
          openapi-python-client generate --path openapi-terraform-cloud/specifications/openapi-terraform-cloud.json  
          cp -r terraform-cloud-client/terraform_cloud_client src
          rm -rf terraform-cloud-client
          ls -ltrh src

 
      - name: Build and publish
        env:
          TWINE_USERNAME: $
          TWINE_PASSWORD: $
        run: |
          ls -ltrh 
          python3 -m build
          ls -ltrh dist
#          twine upload dist/*

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform_cloud_client.whl
          path: src/terraform_cloud_client-0.0.1-py3-none-any.whl
